/*
 * This file is generated by jOOQ.
 */
package com.sunshine.nacos.client.jooq.test01;


import com.sunshine.nacos.client.jooq.test01.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test01
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test01.user</code>.
     */
    public static final User USER = com.sunshine.nacos.client.jooq.test01.tables.User.USER;
}
