/*
 * This file is generated by jOOQ.
 */
package com.sunshine.alibaba.cloud.jooq.laboratory.tables.records;


import com.sunshine.alibaba.cloud.jooq.laboratory.tables.FlowRule;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FlowRuleRecord extends UpdatableRecordImpl<FlowRuleRecord> implements Record2<UInteger, String> {

    private static final long serialVersionUID = -577241017;

    /**
     * Setter for <code>spring_cloud_alibaba_laboratory.flow_rule.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>spring_cloud_alibaba_laboratory.flow_rule.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>spring_cloud_alibaba_laboratory.flow_rule.flow_rule</code>.
     */
    public void setFlowRule(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>spring_cloud_alibaba_laboratory.flow_rule.flow_rule</code>.
     */
    public String getFlowRule() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UInteger, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UInteger, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return FlowRule.FLOW_RULE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return FlowRule.FLOW_RULE.FLOW_RULE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getFlowRule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFlowRule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FlowRuleRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FlowRuleRecord value2(String value) {
        setFlowRule(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FlowRuleRecord values(UInteger value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FlowRuleRecord
     */
    public FlowRuleRecord() {
        super(FlowRule.FLOW_RULE);
    }

    /**
     * Create a detached, initialised FlowRuleRecord
     */
    public FlowRuleRecord(UInteger id, String flowRule) {
        super(FlowRule.FLOW_RULE);

        set(0, id);
        set(1, flowRule);
    }
}
