/*
 * This file is generated by jOOQ.
 */
package com.sunshine.alibaba.cloud.jooq.laboratory;


import com.sunshine.alibaba.cloud.jooq.laboratory.tables.FlowRule;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>spring_cloud_alibaba_laboratory</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLOW_RULE_PRIMARY = Indexes0.FLOW_RULE_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index FLOW_RULE_PRIMARY = Internal.createIndex("PRIMARY", FlowRule.FLOW_RULE, new OrderField[] { FlowRule.FLOW_RULE.ID }, true);
    }
}
