/*
 * This file is generated by jOOQ.
 */
package com.sunshine.alibaba.cloud.jooq.laboratory;


import com.sunshine.alibaba.cloud.jooq.laboratory.tables.FlowRule;
import com.sunshine.alibaba.cloud.jooq.laboratory.tables.records.FlowRuleRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.UInteger;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>spring_cloud_alibaba_laboratory</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<FlowRuleRecord, UInteger> IDENTITY_FLOW_RULE = Identities0.IDENTITY_FLOW_RULE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlowRuleRecord> KEY_FLOW_RULE_PRIMARY = UniqueKeys0.KEY_FLOW_RULE_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<FlowRuleRecord, UInteger> IDENTITY_FLOW_RULE = Internal.createIdentity(FlowRule.FLOW_RULE, FlowRule.FLOW_RULE.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<FlowRuleRecord> KEY_FLOW_RULE_PRIMARY = Internal.createUniqueKey(FlowRule.FLOW_RULE, "KEY_flow_rule_PRIMARY", FlowRule.FLOW_RULE.ID);
    }
}
