/*
 * This file is generated by jOOQ.
 */
package com.sunshine.alibaba.cloud.jooq.laboratory;


import com.sunshine.alibaba.cloud.jooq.laboratory.tables.FlowRule;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpringCloudAlibabaLaboratory extends SchemaImpl {

    private static final long serialVersionUID = 1835065789;

    /**
     * The reference instance of <code>spring_cloud_alibaba_laboratory</code>
     */
    public static final SpringCloudAlibabaLaboratory SPRING_CLOUD_ALIBABA_LABORATORY = new SpringCloudAlibabaLaboratory();

    /**
     * The table <code>spring_cloud_alibaba_laboratory.flow_rule</code>.
     */
    public final FlowRule FLOW_RULE = com.sunshine.alibaba.cloud.jooq.laboratory.tables.FlowRule.FLOW_RULE;

    /**
     * No further instances allowed
     */
    private SpringCloudAlibabaLaboratory() {
        super("spring_cloud_alibaba_laboratory", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            FlowRule.FLOW_RULE);
    }
}
