/*
 * This file is generated by jOOQ.
 */
package com.sunshine.alibaba.cloud.jooq.laboratory;


import com.sunshine.alibaba.cloud.jooq.laboratory.tables.FlowRule;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in spring_cloud_alibaba_laboratory
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>spring_cloud_alibaba_laboratory.flow_rule</code>.
     */
    public static final FlowRule FLOW_RULE = com.sunshine.alibaba.cloud.jooq.laboratory.tables.FlowRule.FLOW_RULE;
}
