/*
 * This file is generated by jOOQ.
 */
package com.sunshine.alibaba.cloud.jooq.test01;


import com.sunshine.alibaba.cloud.jooq.test01.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test01 extends SchemaImpl {

    private static final long serialVersionUID = 1850472039;

    /**
     * The reference instance of <code>test01</code>
     */
    public static final Test01 TEST01 = new Test01();

    /**
     * The table <code>test01.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Test01() {
        super("test01", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            User.USER);
    }
}
